# Generated by Django 4.1.1 on 2022-10-30 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_purchase_date_alter_sale_date_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 31, 0, 45, 8, 724036)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 31, 0, 45, 8, 724036)),
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
